### ISSUE TITLE
本地代码部署报错

### ISSUE THREAD

**Issue by GOOLDOVE** [PairZhu/GPT-QQRobot#3]
$ nest start
[2023-03-08T20:21:38.470] [INFO] robot - 开始连接CQHTTP...
[2023-03-08T20:21:38.498] [INFO] robot - CQHTTP连接成功！
[2023-03-08T20:21:38.498] [INFO] robot - 开始获取登录信息...
[2023-03-08T20:21:38.520] [INFO] robot - 登录信息获取成功！
TypeError: Cannot read properties of null (reading 'nickname')
    at Robot.init (file:///C:/Users/Administrator/Desktop/gpt3/GPT-QQRobot-main/src/robot.ts:112:51)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///C:/Users/Administrator/Desktop/gpt3/GPT-QQRobot-main/src/main.ts:18:1

**Comment by PairZhu** [comment]
你cq-http的版本是多少

**Comment by GOOLDOVE** [comment]
v1.0.0-rc4

**Comment by GOOLDOVE** [comment]
> 你cq-http的版本是多少

v1.0.0-rc4

**Comment by GOOLDOVE** [comment]
> 你cq-http的版本是多少

cqhttp正常通信，需要倒版本安装吗

**Comment by PairZhu** [comment]
不应该啊，我这里是没问题的。你会一点js吗？如果会的话你看看robot.ts里http请求的结果输出一下我看看，如果不会的话只能加一下我的qq了1115306638

**Comment by GOOLDOVE** [comment]
已解决，问题出在.env环境里配置http与ws时加入了/，例如http://127.0.0.1:5700，后面不能带有/
